services:
  db:
    image: public.ecr.aws/docker/library/postgres:17
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cv_ai_user -d cv_ai_db"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - apps/api/.env.docker
    volumes:
      - ./apps/api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data: