# Generated by Django 6.0.3 on 2026-03-20 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class', models.IntegerField()),
                ('predicted_label', models.CharField(max_length=50)),
                ('probability_ok', models.FloatField()),
                ('probability_defect', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_prediction', to='core.inspection')),
            ],
        ),
    ]
