FROM public.ecr.aws/docker/library/python:3.13-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY apps/api /app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]